CREATE TABLE  "APARCAMIENTOSMOTOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TITULO" VARCHAR2(50), 
	"DESCRIPCION" VARCHAR2(500), 
	"PLAZAS" NUMBER, 
	"LAST_UPDATE" VARCHAR2(50), 
	"LATITUD" NUMBER, 
	"LONGITUD" NUMBER, 
	"ICONO" VARCHAR2(500)
   ) ;
   
   CREATE TABLE  "BICEBERG" 
   (	"LINK" VARCHAR2(500), 
	"TITULO" VARCHAR2(500), 
	"ICONO" VARCHAR2(500), 
	"LATITUD" NUMBER, 
	"LONGITUD" NUMBER, 
	"ID" NUMBER NOT NULL ENABLE
   ) ;